name: release ws-server exe

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup py
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install deps
        run: python -m pip install --upgrade pip && pip install pyinstaller websockets pynput pystray Pillow pyperclip PyQt6 hidapi winotify

      - name: build ws-server exe
        run: python -m PyInstaller --onefile --windowed --add-data "assets;assets" --add-data "services;services" --icon="assets/icon.ico" --name="input-overlay-ws" --hidden-import=services.consts --hidden-import=services.settings --hidden-import=winotify input-overlay-ws.py

      - name: create windows zip
        run: mkdir windows-release && copy dist\input-overlay-ws.exe windows-release\ && powershell Compress-Archive -Path windows-release\* -DestinationPath input-overlay-ws-windows.zip

      - name: attest windows build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: input-overlay-ws-windows.zip

      - name: make release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            input-overlay-ws-windows.zip
          body: |
            ## input-overlay websocket server ${{ github.ref_name }}
            
            **windows:**
            - download `input-overlay-ws-windows.zip`
            - unzip and run `input-overlay-ws.exe`
            - Right-click the tray icon for settings
            
            ---
            
            [CHANGELOG.md](https://github.com/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.ref_name }}) for details on what's new in this release.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}